version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-1:891377176411:task-definition/lkg-class-manager:1" 
        LoadBalancerInfo:
          ContainerName: "book_manager"
          ContainerPort: 8080
